import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'GOCART ADMIN',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen flex flex-col`}
      >
        <div className="flex flex-col h-full gap-2 ">
          <div className="w-full h-[5%] bg-red-500">Header</div>
          <div className="flex flex-grow">{children}</div>
          <div className="w-full h-[5%] bg-pink-500">Footer</div>
        </div>
      </body>
    </html>
  )
}
